# path to ROSETTA
rosettadir: /home/iwe14/ML_Rosetta/rosetta.source.release-362/

# Path to working directory
workdir: /home/iwe14/Documents/test

# List of samples
samples:
  - MERS

# Tag used to distinguish output variants
tag: test
