# path to ROSETTA
rosettadir: /PATH/TO/YOUR/ROSETTA

# Path to working directory
workdir: /PATH/TO/YOUR/WORKING/DIRECTORY

inputdir: PATH/TO/GITHUB/REPO/input_files

# List of samples
samples: SAMPLE_NAME
